### ISSUE TITLE
TBCC Update

### ISSUE THREAD

**Issue by Macumbafeh** [Schaka/BuffLib#3]
Hello Schaka !

I saw you were updating your addons for TBCC, and it's nice to see you in the party again ;).

I contributed with the update of Gladdy with Knall (Xicon) for TBCC. 

I just wanted to know if you will update BuffLib or something similar for TBCC, since we can't see buff duration on enemy target?

Thanks in advance !

**Comment by Schaka** [comment]
Wait, when did they change it so you can't see the duration of buffs on enemy targets? It worked until like 2 days ago.
BuffLib won't work, btw. I tried to port it just for fun a while ago and tainting secure functions such as UnitBuff and UnitDebuff, leads to a taint and breaks the entire UI.

**Comment by Macumbafeh** [comment]
Yeah that's why i closed it. I forgot to add an other comment.
Idk what blizzard is doing. It wasn't working and now it's fine...

Thanks anyway
